root /opt/domjudge/domserver/webapp/public;
client_max_body_size 0;
send_timeout 36000s;

access_log /var/log/nginx/domjudge-access.log;
error_log /var/log/nginx/domjudge-error.log warn;

more_clear_headers Server;
add_header Content-Security-Policy "object-src 'self'; frame-ancestors 'self';" always;
add_header Referrer-Policy "same-origin" always;
add_header X-Content-Type-Options "nosniff" always;
add_header X-Frame-Options "DENY" always;
add_header X-XSS-Protection "1; mode=block" always;

location / {
    try_files $uri @domjudge_front;
}

location /api/ {
    try_files $uri @domjudge_api;
}

location @domjudge_front {
    fastcgi_split_path_info ^(.+\.php)(/.*)$;
    fastcgi_pass domjudge_php;
    include fastcgi_params;
    fastcgi_param SERVER_NAME $host;
    fastcgi_param SCRIPT_FILENAME /opt/domjudge/domserver/webapp/public/index.php;
    fastcgi_param SCRIPT_NAME /index.php;
    fastcgi_param REQUEST_URI $uri?$args;
    fastcgi_param DOCUMENT_ROOT /opt/domjudge/domserver/webapp/public;
    fastcgi_param HTTPS $fastcgi_param_https_variable;
    internal;
}

location @domjudge_api {
    fastcgi_split_path_info ^(.+\.php)(/.*)$;
    fastcgi_pass domjudge_php;
    include fastcgi_params;
    fastcgi_param SERVER_NAME $host;
    fastcgi_param SCRIPT_FILENAME /opt/domjudge/domserver/webapp/public/index.php;
    fastcgi_param SCRIPT_NAME /index.php;
    fastcgi_param REQUEST_URI $uri?$args;
    fastcgi_param DOCUMENT_ROOT /opt/domjudge/domserver/webapp/public;
    fastcgi_param HTTPS $fastcgi_param_https_variable;
    internal;
}
